#!/bin/bash
cd $(dirname "$0")/../..

S=shipreq-dev

tmux -2 new-session -d -s $S \
  && tmux rename-window ctl \
  && tmux split-window -h \
  && tmux select-pane -t 0 \
  && tmux send-keys "clear; sbt 'project webapp' restart shell" C-m \
  && tmux select-pane -t 1 \
  && tmux send-keys "clear; cd webapp && grunt watch" C-m

#tmux select-window -t $S:0
tmux -2 attach-session -t $S

#tmux new-window -t $S:0 -n 'Logs'
