# https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md

buildRoots = [ "Code" ]

updates.pin  = [
  { groupId = "com.github.japgolly.scalajs-react", version = "2." },
  { groupId = "com.squareup.okhttp3", version = "3." },
  { groupId = "org.eclipse.jetty", version = "9." },
  { groupId = "javax.servlet", artifactId="javax.servlet-api", version = "3.1." },
  { groupId = "javax.websocket", artifactId="javax.websocket-api", version = "1.0" }
]
