#!/bin/bash

function dir {
  echo
  echo "$1"
  ls -l "$1"
}

clear
cd "$(dirname "$(readlink -e "$0")")" || exit 1
./gulp "$@"

dir ../webapp-server/src/main/webapp/dev
dir ../webapp-server/src/main/webapp/a
