#!/bin/bash

function dir {
  echo
  echo "$1"
  ls -l "$1"
}

clear
cd "$(dirname "$(readlink -e "$0")")" || exit 1
node_modules/.bin/gulp "$@"

dir ../webapp-server/src/main/webapp/assets
dir ../webapp-server/src/main/webapp/a
