#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
[ -z "$GCP_PROJECT" ] && echo "Use ./target to target an environment first." && exit 1

set -e

function log { echo -e "\033[1;33m$*\033[0m" ;}

# Ensure pwgen installed
pwgen 16 1 >/dev/null

log "Logging Kubernetes into cluster..."

./cluster-login

log "Creating service account key..."

$gcloud iam service-accounts keys create $ENVTMP/taskman-key.json --iam-account taskman@$GCP_PROJECT.iam.gserviceaccount.com

kubectl create secret generic taskman-service-account --from-file=credentials.json=$ENVTMP/taskman-key.json

log "Creating DB account..."

TASKMAN_DB_USERNAME=taskman

TASKMAN_DB_PASSWORD=$(pwgen 64 1)

$gcloud sql users create $TASKMAN_DB_USERNAME host --instance=$DB_INSTANCE --password=$TASKMAN_DB_PASSWORD

echo "
db.host     = localhost
db.database = shipreq
db.username = $TASKMAN_DB_USERNAME
db.password = $TASKMAN_DB_PASSWORD
" > $ENVTMP/taskman-secret.properties

kubectl create secret generic taskman-secrets --from-file=secret.properties=$ENVTMP/taskman-secret.properties

log "Done."
