apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: taskman
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: taskman
    spec:
      containers:

      - name: taskman
        image: "$GCP_GCR_IO/$GCP_PROJECT/taskman:latest"
        imagePullPolicy: Always
        env:
        - name: db_port
          value: "5100"
        resources:
          requests:
            cpu: "0.3"
            memory: "365Mi"
          limits:
            cpu: "0.5"
            memory: "448Mi"
        volumeMounts:
        - name: taskman-props
          mountPath: /taskman/conf
        - name: taskman-secrets
          mountPath: /taskman/secrets
        livenessProbe:
          exec:
            command:
            - /taskman/bin/healthcheck
            - /taskman/taskman.lives
          initialDelaySeconds: 60
          periodSeconds: 60

      - name: taskman-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=$GCP_PROJECT:$GCP_REGION:$DB_INSTANCE=tcp:5100",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: taskman-sql-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: taskman-sql
            mountPath: /cloudsql
          - name: ssl-certs
            mountPath: /etc/ssl/certs

      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: taskman-props
        configMap:
          name: taskman-props
      - name: taskman-secrets
        secret:
          secretName: taskman-secrets
      - name: taskman-sql-credentials
        secret:
          secretName: taskman-service-account
      - name: taskman-sql
        emptyDir:
