#!/bin/bash
cd "$(dirname "$(readlink -e "$0")")" || exit 1
# [ $# -ne 1 ] && echo "Usage: $0 <xxx>" && exit 1
# tmp=/tmp/$(date +%Y%m%d-%H%M%S)-$$

# gcloud deployment-manager deployments create taskman --config dm.yml --preview
gcloud deployment-manager deployments update taskman --config dm.jinja --preview
