#!/bin/bash

[ $# -ne 1 ] && echo "Usage: $0 <ip>" && exit 1
name=private
ip="$1"

echo "=== Adding ($ip)"
ec2-authorize "$name" -P tcp -p -1 --cidr "$ip"/32
echo

echo "=== Confirmation"
ec2-describe-group "$name"

