#!/bin/bash

name=private

echo "=== Creating"
ec2-create-group $name --description "Intra-AWS access only. No public access."
echo

groupId="$(ec2-describe-group $name | fgrep GROUP | perl -pe 's/^.*?\s+(sg-.+?)\s+.*$/\1/')"
[ -z "$groupId" ] && echo "Couldn't determine group id for $name." && exit 1

