#!/bin/bash

name=webapp

echo "=== Creating"
ec2-create-group $name --description "Rules for the webapp server."
echo

groupId="$(ec2-describe-group $name | fgrep GROUP | perl -pe 's/^.*?\s+(sg-.+?)\s+.*$/\1/')"
[ -z "$groupId" ] && echo "Couldn't determine group id for $name." && exit 1

echo "=== Rules"
ec2-authorize $groupId -P tcp -p 80
ec2-authorize $groupId -P tcp -p 443
ec2-authorize $groupId -P icmp -t 0:-1
ec2-authorize $groupId -P icmp -t 3:-1
ec2-authorize $groupId -P icmp -t 8:-1
ec2-authorize $groupId -P icmp -t 11:-1
ec2-authorize $groupId -P icmp -t 0:-1 --egress
ec2-authorize $groupId -P icmp -t 3:-1 --egress
ec2-authorize $groupId -P icmp -t 8:-1 --egress


# Summary of ICMP (RFC792) Message Types
# Type   Name                    Issues
#  0     Echo Reply              Used in probes, tunneling, DoS
#  3     Destination Unreachable Improves performance, used in probes
#  4     Source Quench           Improves performance
#  5     Redirect                Improve local perf, local DoS
#  8     Echo                    Used in probes, DoS
#  9     Router Advertisement    Local use only
# 10     Router Selection        Local use only
# 11     Time Exceeded           Used in traceroute, probes
# 12     Parameter Problem       Report header errors, used in probes
# 13     Timestamp               Used in probes
# 14     Timestamp Reply         Can be used in probes
# 15     Information Request     Obsolete
# 16     Information Reply       Obsolete
# 17     Address Mask Request    Local use okay, useful in probes
# 18     Address Mask Reply      Only routers should reply, probes
# 30     Traceroute              Possible replacement for traceroute
