#!/bin/bash

name=private

echo "=== Removing"
ec2-describe-group "$name" | grep tcp | awk '{print $10}' | while read ip; do
  ec2-revoke "$name" -P tcp -p -1 -s "$ip"
done
echo

echo "=== Confirmation"
ec2-describe-group "$name"

