#!/bin/bash

[ -z "$1" ] && echo "Usage: $0 <group name>" && exit 1
name="$1"

echo "=== Removing"
ec2-describe-group "$name" | grep "tcp	22	" | awk '{print $10}' | while read ip; do
  ec2-revoke "$name" -P tcp -p 22 -s "$ip"
done
echo

echo "=== Confirmation"
ec2-describe-group "$1"

