-XX:+UnlockExperimentalVMOptions

# This will one day be enabled by default
-XX:+UseCGroupMemoryLimitForHeap

# All memory in container is for the JVM
-XX:MaxRAMFraction=1

# Be specific about the GC we want
-XX:+UseG1GC

# Use Graal's JIT
-Dgraal.ShowConfiguration=verbose
-Dgraal.MitigateSpeculativeExecutionAttacks=None
-XX:+EagerJVMCI

# Useful for diagnostics
-XX:+PrintFlagsFinal
-XX:+UnlockDiagnosticVMOptions
-XX:+PrintActiveCpus
-XshowSettings:vm
