db.pool.maximumPoolSize            = 4

shipreq.attack_frustration_delay   = 120 ms
shipreq.feature.publicRegistration = true
shipreq.taskman.schema             = taskman
shipreq.taskman.init.retry.delay   = 3 sec
shipreq.token.length               = 49
shipreq.token.lifespan.register    = 3 days
shipreq.token.lifespan.resetpw     = 24 hours
shipreq.trace.scheduledDelaySec    = 1

