#!/bin/bash

u=shipreq
h=/home/$u

groupadd app

chmod 644 /etc/resolv.conf

useradd -m -g app -s /bin/bash $u \
  && mkdir -m 700 $h/.ssh \
  && cp /root/.ssh/authorized_keys $h/.ssh \
  && chown $u:app $h/.ssh $h/.ssh/authorized_keys \
  && touch /etc/authbind/byport/{80,443} \
  && chown $u /etc/authbind/byport/{80,443} \
  && chmod 755 /etc/authbind/byport/{80,443} \
  && ls -la $h
