#!/bin/bash

[ -z "$1" ] && echo "Usage: $0 <public DNS>" && exit 1

cd "$(dirname "$0")"

war=webapp/webapps/shipreq.war

rsync -vcRptih $war $(<username)@"$1":

echo
sha1sum $war | sed 's/$/ (local)/'
ssh $(<username)@"$1" "sha1sum $war" | sed 's/$/ (remote)/'
