#!/bin/bash

cd "$(dirname "$0")"

d=../Code/webapp/target/scala-2.10/
s="$(ls -1rt $d | fgrep .war | tail -1)"
[ -z "$s" ] && echo "No WARs found in $d" && exit 1
echo "Found: $s"

echo "Installing..."
cp -p $d/$s webapp/webapps/shipreq.war \
  && echo && webapp/compress_static_resources_in_war \
  && echo && webapp/inspect-war
