#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

./build

docker run --rm \
  -it \
  -e DNS_TTL=10s \
  -e GRAFANA_URL=http://grafana:3000 \
  -e JAEGER_URL= \
  -e KIBANA_URL=http://kibana.localhost \
  -e PROMETHEUS_URL=http://prometheus:9090/ \
  -e SHIPREQ_ENV=test \
  -e SHIPREQ_URL_HTTP=http://shipreq.localhost \
  -e SHIPREQ_URL=https://shipreq.localhost \
  shipreq/ops/portal