-- CREATE USER golly PASSWORD 'g';

\c shipreq_dev
GRANT CONNECT ON DATABASE shipreq_dev TO golly;
GRANT ALL ON ALL TABLES IN SCHEMA public TO golly;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO golly;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO golly;

\c shipreq_test
GRANT CONNECT ON DATABASE shipreq_test TO golly;
GRANT ALL ON ALL TABLES IN SCHEMA public TO golly;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO golly;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO golly;

\c shipreq_prod
GRANT CONNECT ON DATABASE shipreq_prod TO golly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO golly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO golly;
--GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO golly;

