{
 "title": "Wall (managed)",
 "description": "Meant for wall display",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "time_range", "query": "24h" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count (node_exporter_build_info)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "min(node_time_seconds - on(instance) node_boot_time_seconds)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{ecs_name=~\".+\"}) / sum(ecs_service_desired_tasks)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "time() - max(container_start_time_seconds{ecs_name=~\".+-shipreq-webapp\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "time() - max(container_start_time_seconds{ecs_name=~\".+-shipreq-taskman\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "time() - max (container_start_time_seconds{ecs_name!=\"\",ecs_name!~\".+-shipreq-(?:webapp|taskman)\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(shipreq_webapp_secure_events_total[$time_range]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(logback_appender_total{level=~\"[wW].*\"}[$time_range]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(logback_appender_total{level=~\"[eEfF].*\"}[$time_range]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(max_over_time(shipreq_daily_logins_total{unique_user=\"y\"}[$time_range]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(max_over_time(shipreq_webapp_ws_open[$time_range]))"
    }
   ]
  },
  {
   "title": "Users",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(shipreq_users_total{user_type=\"staff\",registered=\"y\"}[$__interval])",
     "legendFormat": "(staff) registered"
    },
    {
     "expr": "avg_over_time(shipreq_users_total{user_type=\"public\",registered=\"y\"}[$__interval])",
     "legendFormat": "(public) registered"
    },
    {
     "expr": "avg_over_time(shipreq_users_total{user_type=\"public\",registered=\"n\"}[$__interval])",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Engagement",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "min(avg_over_time(shipreq_users_last_login_seconds_ago{user_type=\"staff\"}[$__interval]))",
     "legendFormat": "(staff) last login"
    },
    {
     "expr": "min(avg_over_time(shipreq_project_last_access_seconds_ago{owner_type=\"staff\",access=\"w\"}[$__interval]))",
     "legendFormat": "(staff) last write"
    },
    {
     "expr": "min(avg_over_time(shipreq_users_last_login_seconds_ago{user_type=\"public\"}[$__interval]))",
     "legendFormat": "(public) last login"
    },
    {
     "expr": "min(avg_over_time(shipreq_project_last_access_seconds_ago{owner_type=\"public\",access=\"w\"}[$__interval]))",
     "legendFormat": "(public) last write"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time(shipreq_projects_total{owner_type=\"staff\"}[$__interval])",
     "legendFormat": "staff"
    },
    {
     "expr": "avg_over_time(shipreq_projects_total{owner_type=\"public\"}[$__interval])",
     "legendFormat": "public"
    },
    {
     "expr": "sum(avg_over_time(shipreq_projects_total[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Events",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time(shipreq_events_total{owner_type=\"staff\",initial=\"n\"}[$__interval])",
     "legendFormat": "staff"
    },
    {
     "expr": "avg_over_time(shipreq_events_total{owner_type=\"public\",initial=\"n\"}[$__interval])",
     "legendFormat": "public"
    },
    {
     "expr": "sum(avg_over_time(shipreq_events_total{initial=\"n\"}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Reqs",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum (avg_over_time(shipreq_reqs_total{owner_type=\"staff\"}[$__interval]))",
     "legendFormat": "staff"
    },
    {
     "expr": "sum (avg_over_time(shipreq_reqs_total{owner_type=\"public\"}[$__interval]))",
     "legendFormat": "public"
    },
    {
     "expr": "sum (avg_over_time(shipreq_reqs_total[$__interval]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}