#!/bin/bash
cd "$(dirname "$0")" || exit 1

exec docker run \
  --rm \
  --privileged \
  --network host \
  -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v"$(pwd)/../../Code":/Code:ro \
  -v"$HOME/.coursier/cache":/root/.cache/coursier:ro \
  -e SHIPREQ_TARGET=/tmp/shipreq.sbt \
  -e SHIPREQ_RELEASE_TARGET=/tmp/shipreq-release.sbt \
  -m 15G \
  -w /Code \
  shipreq/build:latest \
  bash
