#!/bin/bash
url=http://localhost:8080

function run { ab -d -H 'Accept-Encoding: gzip, deflate, br' "$@"; }
function warm {
  echo ================================================================================
  echo "${@: -1}"
  echo
  run -c1 -n10000 "$@"
}

# Warm up / with and without a session
session="$(curl -v http://localhost:8080 2>&1 | grep JSESSIONID | perl -pe 's/;.*//; s/.*(?=JSESSIONID)//')"
warm $url/
warm -C "$session" $url/

# Extract relative URLs from / and warm those up too
links="$( curl -H "Cookie: $session" $url/ 2>/dev/null | egrep -o '(href|src)=['"'"'"][^"'"'"']*['"'"'"]' | fgrep -v :// | perl -pe 's/^.*?['"'"'"]//;s/['"'"'"]$//'|sort -u )"
for link in $links; do
  u="${url}$link"
  warm -C "$session" $u
done
